@URL = http://localhost:8888

###
GET {{URL}}/api/v1/echo
Content-Type: application/json

### all posts
GET {{URL}}/api/v1/allPosts
Content-Type: application/json

### post by id
GET {{URL}}/api/v1/post/63
Content-Type: application/json

### insert post
POST {{URL}}/api/v1/postNew
Content-Type: application/json

{
  "id": 0,
  "part": "2022",
  "text": "b1",
  "theme": "b1",
  "title": "b1"
}

### update post
POST {{URL}}/api/v1/postUpdate
Content-Type: application/json

{
  "id": 553,
  "part": "2022",
  "text": "bb",
  "theme": "bb",
  "title": "bb"
}

### delete post by id
POST {{URL}}/api/v1/postDelete/63
Content-Type: application/json


