@URL = http://localhost:8888

### common graphs (activ3)
GET {{URL}}/api/v1/common_graphs/2022-09-01/2022-10-01
Content-Type: application/json


### individual graphs (activ4)
GET {{URL}}/api/v1/individual_graphs/2022-09-01/2022-10-01
Content-Type: application/json


### параметры текущего месяца
GET {{URL}}/api/v1/analytic_params
Content-Type: application/json
